### ISSUE TITLE
Language - Country Mapping

### ISSUE THREAD

**Issue by kev007** [kev007/ARTFUL#42]
See: https://github.com/kev007/ARTFUL/blob/frontend/server/src/main/webapp/resources/js/app.js#L240-L270

Structure:
mergedData.features[1].properties.name
mergedData.features[1].properties.frequency

**Comment by kev007** [comment]
[BUGS]
Indonesia - India: incorrect mapping
Outgoing references - cannot select another country without deselecting current country

**Comment by pnancke** [comment]
I'll have a look at it later

**Comment by pnancke** [comment]
The country code for India is `ind` source: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
So the mapping is correct or do you mean something else?

**Comment by kev007** [comment]
Correct, but the language code for India's official language, Hindi, is `hin`
The language code `ind` is for Bahasa Indonesia

For reference: https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by kev007** [comment]
Another problem: both the languages Xhosa `xho` and Afrikaans `afr` need to be mapped to South Africa

**Comment by pnancke** [comment]
The issue with outgoing references and selecting different countries successivly should be fixed with https://github.com/kev007/ARTFUL/pull/49. I made a seperate issue for the problem with Xhosa and Afrikaans: https://github.com/kev007/ARTFUL/issues/46. Please reopen this issue or create a new one if you still find something wrong.
